config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :posts do
    resources :comments
  end
  resources :courses do
    resources :matriculas, only: [:create]
  end

  resources :matriculas, only: [:index, :destroy]
  root to: "posts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :matriculas, dependent: :delete_all
  has_many :users, through: :matriculas
  has_many :orders
end

app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :orders
  has_many :matriculas
  has_many :courses, through: :matriculas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = Comment.new(content: params[:comment][:content])
    @comment.user = current_user
    @comment.post_id = params[:post_id]
    @comment.save
    redirect_to post_path(params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      @post = @comment.post
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :authenticate_user!
before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end
  def show
    @matricula = Matricula.new
  end
  def create
    @course = Course.create(course_params)
    redirect_to courses_url, notice: 'has creado un nuevo curso.'
  end
  def new
    @course = Course.new
  end

  def destroy
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: 'Post was successfully destroyed.' }
      end
    end
  end


  private
    def set_course
      @course = Course.find(params[:id])
    end
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController

  before_action :authenticate_user!
  def index
    @user_courses = current_user.courses
  end

  def create
    @matricula = Matricula.new
    @matricula.user = current_user
    @matricula.course = @course = Course.find(params[:course_id])
    @matricula.save

    respond_to do |format|
      if @matricula.save
        format.html { redirect_to matriculas_path, notice: ' ya te Inscribiste felicidades.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { redirect_to courses_url, notice: ' fallo tu inscripcion. #{@matricula.errors.messages} ' }
      end
    end
  end

  def edit
  end

  def destroy
    @matricula = Matricula.where(user: current_user, course: params[:id])
    if @matricula.first.destroy
      respond_to do |format|
        format.html { redirect_to matriculas_url, notice: 'Post was successfully destroyed.' }
      end
    end
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end
  def show

  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user == current_user
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/course_informations_helper.rb
module CourseInformationsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/matriculas/create.html.erb
<h1>Matriculas#create</h1>
<p>Find me in app/views/matriculas/create.html.erb</p>

app/views/matriculas/destroy.html.erb
<h1>Matriculas#destroy</h1>
<p>Find me in app/views/matriculas/destroy.html.erb</p>

app/views/matriculas/edit.html.erb
<h1>Matriculas#edit</h1>
<p>Find me in app/views/matriculas/edit.html.erb</p>

app/views/matriculas/index.html.erb
<h1>Matriculas</h1>


<h1>Cursos seleccionados</h1>

<table>
  <thead>
    <tr>
      <th>cursos seleccionados</th>
      <th>descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= link_to 'Destroy', matricula_path(course), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/matriculas/show.html.erb
<h1>Matriculas#show</h1>
<p>Find me in app/views/matriculas/show.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.try(:name) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

  <strong>Comments:</strong>
  <% @post.comments.each do |comment| %>
  <br>

    <strong><%= comment.user.name %></strong>
      <p>
      <%= comment.content %>
        <td><%= link_to 'Destroy', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </p>
  <% end %>


<%= form_with(model: @comment, url: post_comments_path(@post), local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>